const CV_DATA = {

  personal: {
    name: "Jorge G. Lopez Laveaga",
    title_es: "Tech Project Manager | IA · IoT · Infraestructura Crítica Corporativa",
    title_en: "Tech Project Manager | AI · IoT · Corporate Critical Infrastructure",
    summary_es: "Tech PM con 15+ años ejecutando proyectos de alto impacto para corporativos, gobierno e industria pesada. Portafolios $50M+ USD. BBVA · Daimler · Sodexo · Tren Maya.",
    summary_en: "Tech PM with 15+ years executing high-impact projects for corporates, government, and heavy industry. $50M+ USD portfolios. BBVA · Daimler · Sodexo · Tren Maya.",
    phone: "56 5256-4338",
    emails: ["jorge.lopez.laveaga4589@gmail.com", "ventas@sinaimx.com"],
    linkedin: "https://www.linkedin.com/in/jorgelaveaga/",
    github: "https://github.com/jorgeahmed",
    location: "Ciudad de México, México",
  },

  metrics: {
    budgets: "$2.5M USD",
    projects: "200+",
    years: "15+",
    fiber: "1,000 km",
    successRate: "98%",
  },

  // ── EXPERIENCIA ──────────────────────────────────────────
  experience: [
    {
      id: "sinai",
      company: "Mantenimiento Sinai",
      icon: "domain",
      color: "primary",
      period_es: "May 2023 — Presente",
      period_en: "May 2023 — Present",
      title_es: "Fundador & CEO",
      title_en: "Founder & CEO",
      summary_es: "Empresa de servicios tecnológicos, industriales y de automatización. Portafolio activo de clientes corporativos Fortune 500 con presupuestos multimillonarios.",
      summary_en: "Technology, industrial, and automation services company. Active Fortune 500 corporate client portfolio with multi-million dollar budgets.",
      achievements_es: [
        "Dirección de portafolio de 150+ proyectos para Sodexo, Daimler y Gobierno Federal",
        "Contrato Daimler Santiago: $8.1M MXN — demolición y reforzamiento estructural en planta activa",
        "Contrato Tren Maya: $2.1M MXN — suministro e instalación de biodigestores industriales",
        "Implementación Smart City e IoT para Gobierno de Tabasco (UZUMA): red LPR + LoRa",
        "QuoteBot Vision: app móvil con IA que reduce cotizaciones de 2h a 2 minutos (−98%)",
        "Gestión de transformadores 2,000 KVA para continuidad operativa industrial ($2.6M MXN)",
      ],
      achievements_en: [
        "Portfolio management of 150+ projects for Sodexo, Daimler, and Federal Government",
        "Daimler Santiago contract: $480k USD — demolition and structural reinforcement in active plant",
        "Tren Maya contract: $125k USD — supply and installation of industrial biodigestors",
        "Smart City & IoT implementation for Tabasco Government (UZUMA): LPR + LoRa network",
        "QuoteBot Vision: AI mobile app reducing quotes from 2h to 2 minutes (−98%)",
        "2,000 KVA transformer management for industrial operational continuity ($150k USD)",
      ],
      technologies: ["Project Management", "IoT", "Industrial Automation", "Contract Management", "AI/ML Integration", "B2B"],
    },
    {
      id: "seismicai",
      company: "SeismicAI",
      icon: "crisis_alert",
      color: "orange",
      period_es: "Ago 2023 — Jul 2024",
      period_en: "Aug 2023 — Jul 2024",
      title_es: "Sr. Technical Account Manager / PM de Implementación",
      title_en: "Sr. Technical Account Manager / Implementation PM",
      summary_es: "PM de implementaciones de sistemas de alerta sísmica impulsados por IA para clientes corporativos en México, con BBVA México como cliente ancla.",
      summary_en: "PM for AI-powered seismic alert system implementations for corporate clients in Mexico, with BBVA México as anchor client.",
      achievements_es: [
        "PM de implementación del sistema de alerta sísmica IA para BBVA México (infraestructura bancaria crítica)",
        "Integración de hardware Edge Computing con modelos ML para detección sísmica en tiempo real",
        "Gestión de stakeholders C-Level en BBVA: coordinación entre IT, Seguridad y Operaciones",
        "Protocolo de instalación con tolerancia cero a fallos en 100% de los sitios bancarios",
        "Coordinación entre equipos de ingeniería IoT, data science y operaciones bancarias",
      ],
      achievements_en: [
        "Implementation PM for AI seismic alert system at BBVA México (critical banking infrastructure)",
        "Edge Computing hardware integration with ML models for real-time seismic detection",
        "C-Level stakeholder management at BBVA: coordination between IT, Security, and Operations",
        "Zero-fault-tolerance installation protocol across 100% of banking sites",
        "Coordination between IoT engineering, data science, and banking operations teams",
      ],
      technologies: ["AI/ML", "Edge Computing", "IoT Hardware", "Stakeholder Management", "System Integration", "Risk Management"],
    },
    {
      id: "nomadx",
      company: "No_madxperience",
      icon: "laptop",
      color: "purple",
      period_es: "May 2019 — May 2022",
      period_en: "May 2019 — May 2022",
      title_es: "Fundador — Consultoría Tech & Servicios Digitales",
      title_en: "Founder — Tech Consulting & Digital Services",
      summary_es: "Plataforma de consultoría tecnológica y servicios digitales. Proyectos de automatización, sistemas digitales y consultoría IT para PYMES y startups en México y LATAM.",
      summary_en: "Technology consulting and digital services platform. Automation projects, digital systems, and IT consulting for SMEs and startups in Mexico and LATAM.",
      achievements_es: [
        "Desarrollo e implementación de soluciones digitales para clientes en México y LATAM",
        "Proyectos de automatización de procesos empresariales con herramientas low-code/no-code",
        "Consultoría de transformación digital para empresas en etapa de crecimiento",
        "Gestión de equipos remotos distribuidos durante auge del trabajo remoto (2020–2022)",
      ],
      achievements_en: [
        "Development and implementation of digital solutions for clients in Mexico and LATAM",
        "Business process automation projects using low-code/no-code tools",
        "Digital transformation consulting for growth-stage companies",
        "Remote distributed team management during the remote work boom (2020–2022)",
      ],
      technologies: ["Digital Consulting", "Process Automation", "No-Code/Low-Code", "Remote Management", "Digital Transformation"],
    },
    {
      id: "americantower",
      company: "American Tower / AT&T",
      icon: "cell_tower",
      color: "cyan",
      period_es: "Ago 2017 — May 2019",
      period_en: "Aug 2017 — May 2019",
      title_es: "Gerente Regional de Proyectos — Infraestructura Telco",
      title_en: "Regional Project Manager — Telco Infrastructure",
      summary_es: "Gestión de proyectos de infraestructura de telecomunicaciones: despliegue de fibra óptica, instalación de torres y expansión de red AT&T en región metropolitana.",
      summary_en: "Telecom infrastructure project management: fiber optic deployment, tower installation, and AT&T network expansion in the metropolitan region.",
      achievements_es: [
        "Despliegue de 1,000+ km de fibra óptica para la red AT&T en zona metropolitana de México",
        "Gestión de 50+ torres de telecomunicaciones: mantenimiento preventivo, upgrade y nuevas instalaciones",
        "Coordinación con autoridades municipales y federales para permisos de vía pública",
        "Reducción de tiempos de proyecto en 25% mediante optimización de rutas y recursos de campo",
      ],
      achievements_en: [
        "Deployment of 1,000+ km of fiber optic for AT&T network in Mexico metropolitan area",
        "Management of 50+ telecommunication towers: preventive maintenance, upgrade, and new installations",
        "Coordination with municipal and federal authorities for right-of-way permits",
        "25% project timeline reduction through field route and resource optimization",
      ],
      technologies: ["Fiber Optic", "Telecom Infrastructure", "Network Deployment", "Government Liaising", "Field PM"],
    },
    {
      id: "dragonCFE",
      company: "Grupo Dragón / CFE",
      icon: "bolt",
      color: "yellow",
      period_es: "Nov 2016 — Jun 2017",
      period_en: "Nov 2016 — Jun 2017",
      title_es: "Supervisor de Proyectos — Infraestructura Eléctrica",
      title_en: "Project Supervisor — Electrical Infrastructure",
      summary_es: "Supervisión de proyectos de infraestructura eléctrica para la Comisión Federal de Electricidad (CFE). Instalaciones de alta tensión, subestaciones y tendido eléctrico.",
      summary_en: "Supervision of electrical infrastructure projects for the Federal Electricity Commission (CFE). High-voltage installations, substations, and electrical cabling.",
      achievements_es: [
        "Supervisión de instalaciones eléctricas de alta tensión cumpliendo estrictamente normativas CFE",
        "Coordinación de cuadrillas técnicas especializadas en entornos de alta seguridad eléctrica",
        "Gestión de suministros y logística para proyectos de infraestructura de distribución",
        "Cumplimiento de protocolos de seguridad industrial con cero accidentes durante el período",
      ],
      achievements_en: [
        "Supervision of high-voltage electrical installations meeting strict CFE standards",
        "Coordination of specialized technical crews in high-electrical-safety environments",
        "Supply management and logistics for distribution infrastructure projects",
        "Industrial safety protocol compliance with zero accidents throughout the period",
      ],
      technologies: ["High Voltage", "Electrical Infrastructure", "CFE Standards", "Safety Protocols", "Field Supervision"],
    },
    {
      id: "pretencreto",
      company: "PRETENCRETO",
      icon: "construction",
      color: "green",
      period_es: "Nov 2013 — Jun 2016",
      period_en: "Nov 2013 — Jun 2016",
      title_es: "Jefe de Obra — Manufactura de Concreto Prefabricado",
      title_en: "Site Manager — Precast Concrete Manufacturing",
      summary_es: "Gestión de obras civiles y producción en planta de concreto prefabricado. Supervisión de equipos, control de calidad y logística de entrega de elementos estructurales.",
      summary_en: "Civil works management and plant production at precast concrete facility. Team supervision, quality control, and delivery logistics of structural elements.",
      achievements_es: [
        "Supervisión de producción de elementos prefabricados para proyectos de infraestructura a nivel nacional",
        "Control de calidad de mezclas y armados conforme a normas estructurales NMX y NOM",
        "Gestión de logística de transporte y montaje de elementos estructurales en obra",
        "Optimización de procesos de producción con reducción de desperdicios de material del 15%",
      ],
      achievements_en: [
        "Production supervision of precast elements for infrastructure projects nationwide",
        "Quality control of mixes and reinforcements per NMX and NOM structural standards",
        "Transportation logistics and structural element assembly management at job sites",
        "Production process optimization with 15% material waste reduction",
      ],
      technologies: ["Civil Engineering", "Quality Control", "Precast Concrete", "Logistics", "NOM Standards"],
    },
    {
      id: "santander",
      company: "Santander / Compusof",
      icon: "account_balance",
      color: "blue",
      period_es: "Nov 2010 — Jul 2013",
      period_en: "Nov 2010 — Jul 2013",
      title_es: "Supervisor QA — Infraestructura Bancaria IT",
      title_en: "QA Supervisor — Banking IT Infrastructure",
      summary_es: "Supervisión de calidad en proyectos de infraestructura tecnológica para Santander México. Control de instalaciones, cableado estructurado y equipos en sucursales bancarias.",
      summary_en: "Quality supervision for technology infrastructure projects at Santander México. Installation control, structured cabling, and equipment management at bank branches.",
      achievements_es: [
        "Supervisión QA de instalaciones tecnológicas en sucursales Santander a nivel nacional",
        "Control de calidad de cableado estructurado Cat6 y redes LAN en entornos bancarios",
        "Gestión de inventarios de equipos de cómputo y periféricos en plataforma bancaria",
        "Base sólida en disciplina operativa, estándares corporativos y trabajo en entornos regulados",
      ],
      achievements_en: [
        "QA supervision of technology installations at Santander branches nationwide",
        "Quality control of Cat6 structured cabling and LAN networks in banking environments",
        "Computer equipment and peripherals inventory management for banking platform",
        "Solid foundation in operational discipline, corporate standards, and regulated environments",
      ],
      technologies: ["Structured Cabling", "IT Infrastructure", "QA/QC", "Banking Systems", "Network Installation"],
    },
  ],

  // ── PROYECTOS PROFESIONALES ──────────────────────────────
  projects: [
    {
      id: "bbva",
      title: "BBVA México | Sistema de Alerta Sísmica IA",
      client: "BBVA México",
      category: "corporate",
      value: "Enterprise",
      period: "2023–2024",
      icon: "crisis_alert",
      color: "blue",
      tags: ["AI/ML", "Edge Computing", "Banking", "IoT"],
      summary_es: "PM de implementación de sistema de alerta sísmica crítica con IA para infraestructura bancaria. Integración hardware Edge + modelos ML. Tolerancia cero a fallos.",
      summary_en: "Implementation PM for AI-powered critical seismic alert system for banking infrastructure. Edge hardware + ML model integration. Zero tolerance for failure.",
      challenge_es: "BBVA requería un sistema de alerta sísmica con IA que operara en infraestructura bancaria crítica con disponibilidad 99.9%+ y sin impacto a las operaciones bancarias durante la instalación.",
      challenge_en: "BBVA required an AI seismic alert system operating in critical banking infrastructure with 99.9%+ uptime and zero operational impact during installation.",
      solution_es: "Coordiné la integración de hardware Edge Computing con modelos ML entrenados para detección sísmica. Diseñé el protocolo de instalación en horarios no operativos y gestioné stakeholders C-Level en IT, Seguridad y Operaciones.",
      solution_en: "Coordinated Edge Computing hardware integration with trained ML models for seismic detection. Designed installation protocol during non-operating hours and managed C-Level stakeholders in IT, Security, and Operations.",
      outcome_es: "Sistema de alerta sísmica con IA desplegado exitosamente en infraestructura bancaria BBVA. 100% de sitios operativos con protocolo de tolerancia cero a fallos.",
      outcome_en: "AI seismic alert system successfully deployed across BBVA banking infrastructure. 100% of sites operational with zero-fault-tolerance protocol.",
      stack: ["Edge Computing", "ML Models", "Python", "IoT Sensors", "Banking APIs", "Real-time Processing"],
      metrics_es: [{ label: "Tolerancia", value: "0 fallos" }, { label: "Sector", value: "Banca" }, { label: "Tech", value: "Edge+ML" }],
      metrics_en: [{ label: "Tolerance", value: "0 failures" }, { label: "Sector", value: "Banking" }, { label: "Tech", value: "Edge+ML" }],
    },
    {
      id: "daimler",
      title: "Daimler Santiago | Desmantelamiento Industrial",
      client: "Daimler México",
      category: "industrial",
      value: "$8.1M MXN",
      period: "2024",
      icon: "precision_manufacturing",
      color: "orange",
      tags: ["Industrial", "Safety", "Demolition", "Civil"],
      summary_es: "PM de proyecto $8.1M MXN: demolición de líneas de pintura automotriz y reforzamiento estructural en planta activa. 100% cumplimiento en seguridad Daimler.",
      summary_en: "PM of $480k USD project: automotive paint line demolition and structural reinforcement in active plant. 100% Daimler safety compliance.",
      challenge_es: "Demoler las líneas de pintura automotriz en la planta de Daimler Santiago mientras la fábrica continuaba operando, cumpliendo los estrictos protocolos de seguridad de Daimler y sin interrumpir la producción.",
      challenge_en: "Demolish automotive paint lines at the Daimler Santiago plant while the factory continued operating, meeting Daimler's strict safety protocols without disrupting production.",
      solution_es: "Diseñé un plan de trabajo por fases con ventanas de intervención coordinadas con producción. Implementé barreras de seguridad, protocolos de polvo y vibración, y gestioné subcontratistas especializados en demolición industrial.",
      solution_en: "Designed a phased work plan with intervention windows coordinated with production. Implemented safety barriers, dust and vibration protocols, and managed specialized industrial demolition subcontractors.",
      outcome_es: "Proyecto completado en tiempo y dentro del presupuesto. 100% cumplimiento en los estándares de seguridad Daimler con cero accidentes. Planta operó sin interrupciones durante toda la obra.",
      outcome_en: "Project completed on time and within budget. 100% compliance with Daimler safety standards with zero accidents. Plant operated without interruptions throughout the work.",
      stack: ["Project Management", "Industrial Safety", "Civil Engineering", "Subcontractor Management", "Daimler Standards"],
      metrics_es: [{ label: "Valor", value: "$8.1M MXN" }, { label: "Seguridad", value: "100%" }, { label: "Accidentes", value: "0" }],
      metrics_en: [{ label: "Value", value: "$480k USD" }, { label: "Safety", value: "100%" }, { label: "Accidents", value: "0" }],
    },
    {
      id: "sodexo",
      title: "Sodexo México | Portafolio 150+ Proyectos",
      client: "Sodexo México",
      category: "corporate",
      value: "$2.5M+ USD",
      period: "2023–Presente",
      icon: "business_center",
      color: "primary",
      tags: ["Portfolio", "Corporate", "Fortune 500", "Facilities"],
      summary_es: "Gestión continua de portafolio multimillonario: mantenimiento crítico, infraestructura industrial y servicios técnicos para clientes Fortune 500 de Sodexo.",
      summary_en: "Continuous management of multi-million dollar portfolio: critical maintenance, industrial infrastructure, and technical services for Sodexo's Fortune 500 clients.",
      challenge_es: "Gestionar simultáneamente 150+ proyectos de mantenimiento e infraestructura para los clientes Fortune 500 de Sodexo, manteniendo SLAs exigentes y presupuestos ajustados en múltiples sitios.",
      challenge_en: "Simultaneously manage 150+ maintenance and infrastructure projects for Sodexo's Fortune 500 clients, maintaining demanding SLAs and tight budgets across multiple sites.",
      solution_es: "Implementé un sistema de gestión de portafolio con priorización dinámica, comunicación ejecutiva semanal con Sodexo, equipos técnicos especializados por vertical (eléctrico, civil, redes) y control financiero por proyecto.",
      solution_en: "Implemented a portfolio management system with dynamic prioritization, weekly executive communication with Sodexo, specialized technical teams by vertical (electrical, civil, networks), and per-project financial control.",
      outcome_es: "Portafolio activo de 150+ proyectos con tasa de éxito 98%. Relación comercial multianual con Sodexo México generando $2.5M+ USD en ingresos acumulados.",
      outcome_en: "Active portfolio of 150+ projects with 98% success rate. Multi-year commercial relationship with Sodexo México generating $2.5M+ USD in cumulative revenue.",
      stack: ["Portfolio Management", "Field Operations", "Electrical", "Civil Works", "Network Infrastructure", "SLA Management"],
      metrics_es: [{ label: "Proyectos", value: "150+" }, { label: "Éxito", value: "98%" }, { label: "Ingresos", value: "$2.5M+" }],
      metrics_en: [{ label: "Projects", value: "150+" }, { label: "Success", value: "98%" }, { label: "Revenue", value: "$2.5M+" }],
    },
    {
      id: "trenmaya",
      title: "Tren Maya | Infraestructura Crítica Nacional",
      client: "Gobierno Federal de México",
      category: "infra",
      value: "$2.1M MXN",
      period: "2024",
      icon: "train",
      color: "green",
      tags: ["Government", "Infrastructure", "Biodigestors", "National"],
      summary_es: "PM de suministro e instalación de biodigestores industriales para el proyecto ferroviario más grande de México. Contrato $2.1M MXN con Gobierno Federal.",
      summary_en: "PM for supply and installation of industrial biodigestors for Mexico's largest railway project. $125k USD contract with Federal Government.",
      challenge_es: "Suministrar e instalar biodigestores industriales en múltiples puntos del corredor del Tren Maya, coordinando con el Gobierno Federal, contratistas generales y logística en zonas de selva y cenotes.",
      challenge_en: "Supply and install industrial biodigestors at multiple Tren Maya corridor points, coordinating with the Federal Government, general contractors, and logistics in jungle and cenote zones.",
      solution_es: "Gestioné la cadena de suministro de biodigestores industriales desde fabricación hasta instalación, coordiné permisos ambientales, transporte especial y cuadrillas técnicas en sitios remotos de la Península de Yucatán.",
      solution_en: "Managed the industrial biodigestor supply chain from manufacturing to installation, coordinated environmental permits, special transport, and technical crews at remote sites on the Yucatán Peninsula.",
      outcome_es: "Proyecto entregado en tiempo con cumplimiento total de especificaciones del Gobierno Federal. Biodigestores operativos en todos los sitios del Corredor Ferroviario Interoceánico.",
      outcome_en: "Project delivered on time with full compliance with Federal Government specifications. Operational biodigestors at all Interoceanic Railway Corridor sites.",
      stack: ["Government Contracting", "Supply Chain", "Environmental Engineering", "Logistics", "Remote Operations"],
      metrics_es: [{ label: "Contrato", value: "$2.1M MXN" }, { label: "Cliente", value: "Gobierno Fed." }, { label: "Sitios", value: "Múltiples" }],
      metrics_en: [{ label: "Contract", value: "$125k USD" }, { label: "Client", value: "Federal Gov." }, { label: "Sites", value: "Multiple" }],
    },
    {
      id: "uzuma",
      title: "UZUMA Tabasco | Smart City & IoT Gubernamental",
      client: "Gobierno de Tabasco",
      category: "automation",
      value: "Contrato Gubernamental",
      period: "2024",
      icon: "smart_display",
      color: "cyan",
      tags: ["Smart City", "IoT", "LoRa", "LPR", "Government"],
      summary_es: "Dirección de implementación de sistema LPR automatizado y red IoT LoRa para el Gobierno de Tabasco. Primer proyecto Smart City de esta escala en el estado.",
      summary_en: "Direction of automated LPR system and LoRa IoT network for the State of Tabasco. First Smart City project at this scale in the state.",
      challenge_es: "Implementar infraestructura Smart City en Tabasco: un sistema LPR (License Plate Recognition) automatizado integrado con una red IoT LoRa de largo alcance para monitoreo gubernamental urbano.",
      challenge_en: "Implement Smart City infrastructure in Tabasco: an automated LPR (License Plate Recognition) system integrated with a long-range LoRa IoT network for urban government monitoring.",
      solution_es: "Diseñé e implementé la arquitectura del sistema LPR con cámaras de reconocimiento automático de placas, conectadas a una plataforma central vía red LoRa. Coordené con autoridades municipales y proveí capacitación al equipo operativo.",
      solution_en: "Designed and implemented the LPR system architecture with automatic license plate recognition cameras, connected to a central platform via LoRa network. Coordinated with municipal authorities and provided operational team training.",
      outcome_es: "Primer sistema Smart City a esta escala en Tabasco, operativo y entregado al Gobierno del Estado. Red IoT LoRa activa con múltiples nodos de monitoreo urbano.",
      outcome_en: "First Smart City system at this scale in Tabasco, operational and delivered to the State Government. Active LoRa IoT network with multiple urban monitoring nodes.",
      stack: ["LoRa IoT", "LPR Technology", "Computer Vision", "Network Architecture", "Government Systems"],
      metrics_es: [{ label: "Tech", value: "LPR+LoRa" }, { label: "Tipo", value: "Smart City" }, { label: "Estado", value: "Tabasco" }],
      metrics_en: [{ label: "Tech", value: "LPR+LoRa" }, { label: "Type", value: "Smart City" }, { label: "State", value: "Tabasco" }],
    },
    {
      id: "casaley",
      title: "Casa Ley | Infraestructura de Red Multisitio",
      client: "Casa Ley",
      category: "infra",
      value: "Enterprise",
      period: "2024",
      icon: "router",
      color: "indigo",
      tags: ["Aruba", "Networking", "Wi-Fi", "Multi-site"],
      summary_es: "Rollout de switches y Access Points Aruba en centros de distribución de Casa Ley. Gestión multisitio coordinada con equipos de IT internos.",
      summary_en: "Aruba switches and Access Points rollout across Casa Ley distribution centers. Coordinated multi-site delivery with internal IT teams.",
      challenge_es: "Actualizar la infraestructura de red en múltiples centros de distribución de Casa Ley con mínima interrupción operativa, coordinando con IT interno y proveedores Aruba.",
      challenge_en: "Upgrade network infrastructure across multiple Casa Ley distribution centers with minimal operational disruption, coordinating with internal IT and Aruba providers.",
      solution_es: "Planifiqué el rollout por fases con ventanas de mantenimiento nocturnas, estandaricé la configuración Aruba para todos los sitios y entregué documentación técnica completa al equipo IT.",
      solution_en: "Planned phased rollout with overnight maintenance windows, standardized Aruba configuration across all sites, and delivered complete technical documentation to IT team.",
      outcome_es: "Red actualizada en todos los centros de distribución con infraestructura Aruba estándar. Conectividad mejorada y reducción de incidencias de red reportadas.",
      outcome_en: "Network updated across all distribution centers with standard Aruba infrastructure. Improved connectivity and reduction in reported network incidents.",
      stack: ["Aruba Networks", "Cisco", "Network Configuration", "Multi-site Management", "Wi-Fi 6"],
      metrics_es: [{ label: "Marca", value: "Aruba" }, { label: "Tipo", value: "Multi-sitio" }, { label: "Tech", value: "Switches+APs" }],
      metrics_en: [{ label: "Brand", value: "Aruba" }, { label: "Type", value: "Multi-site" }, { label: "Tech", value: "Switches+APs" }],
    },
    {
      id: "transformadores",
      title: "Infraestructura Eléctrica | 2,000 KVA",
      client: "Industria / Manufactura",
      category: "infra",
      value: "$2.6M MXN",
      period: "2024",
      icon: "electrical_services",
      color: "yellow",
      tags: ["Power", "Transformers", "Industrial", "HV"],
      summary_es: "Gestión de suministro y logística de transformadores de alta potencia. Continuidad operativa industrial garantizada ($2.6M MXN).",
      summary_en: "High-power transformer supply and logistics management. Industrial operational continuity guaranteed ($150k USD).",
      challenge_es: "Gestionar el suministro, transporte y puesta en marcha de transformadores de 2,000 KVA para instalación industrial, garantizando la continuidad operativa durante el proceso.",
      challenge_en: "Manage supply, transport, and commissioning of 2,000 KVA transformers for industrial installation, guaranteeing operational continuity throughout the process.",
      solution_es: "Coordiné con fabricantes, transportistas especializados y equipos eléctricos para la logística de transformadores de gran tonelaje. Planifiqué la puesta en marcha en horarios de mínima producción.",
      solution_en: "Coordinated with manufacturers, specialized carriers, and electrical teams for heavy-tonnage transformer logistics. Planned commissioning during minimum production windows.",
      outcome_es: "Transformadores instalados y operativos con continuidad eléctrica garantizada. Cero minutos de paro no planificado en producción industrial durante el proceso.",
      outcome_en: "Transformers installed and operational with guaranteed electrical continuity. Zero unplanned production downtime during the process.",
      stack: ["Electrical Engineering", "High Voltage", "Logistics", "Industrial Safety", "Commissioning"],
      metrics_es: [{ label: "Capacidad", value: "2,000 KVA" }, { label: "Valor", value: "$2.6M MXN" }, { label: "Paro", value: "0 min" }],
      metrics_en: [{ label: "Capacity", value: "2,000 KVA" }, { label: "Value", value: "$150k USD" }, { label: "Downtime", value: "0 min" }],
    },
    {
      id: "erp_karen",
      title: "ERP Karen | Sistema de Gestión Operativa",
      client: "Empresa Interna",
      category: "automation",
      value: "Full-stack ERP",
      period: "2025",
      icon: "database",
      color: "purple",
      tags: ["ERP", "React", "Node.js", "PostgreSQL", "Full-stack"],
      summary_es: "PM de desarrollo e implementación de ERP completo: módulos de empleados, nómina, asistencia, vales e incidencias. Stack: React + Node.js + PostgreSQL.",
      summary_en: "PM for development and implementation of complete ERP: employee, payroll, attendance, vouchers, and incident modules. Stack: React + Node.js + PostgreSQL.",
      challenge_es: "La empresa carecía de un sistema centralizado para gestionar empleados, nómina y operaciones. Los procesos manuales consumían tiempo y generaban errores en cálculos de nómina y asistencias.",
      challenge_en: "The company lacked a centralized system to manage employees, payroll, and operations. Manual processes consumed time and generated errors in payroll and attendance calculations.",
      solution_es: "Dirigí el desarrollo e implementación de un ERP full-stack con React (frontend), Node.js (API REST) y PostgreSQL (base de datos). Módulos: empleados, nómina automática, control de asistencias, vales y gestión de incidencias.",
      solution_en: "Led the development and implementation of a full-stack ERP with React (frontend), Node.js (REST API), and PostgreSQL (database). Modules: employees, automatic payroll, attendance control, vouchers, and incident management.",
      outcome_es: "ERP en producción eliminando procesos manuales. Cálculo de nómina automatizado, asistencias digitalizadas y trazabilidad completa de incidencias operativas.",
      outcome_en: "ERP in production eliminating manual processes. Automated payroll calculation, digitized attendance, and complete operational incident traceability.",
      stack: ["React", "Node.js", "PostgreSQL", "REST APIs", "JWT Auth", "Docker"],
      metrics_es: [{ label: "Stack", value: "React+Node" }, { label: "DB", value: "PostgreSQL" }, { label: "Módulos", value: "5+" }],
      metrics_en: [{ label: "Stack", value: "React+Node" }, { label: "DB", value: "PostgreSQL" }, { label: "Modules", value: "5+" }],
    },
  ],

  // ── PROYECTOS GITHUB ─────────────────────────────────────
  github_projects: [
    {
      id: "hecho-metrics",
      title: "Hecho Metrics — SaaS Full-Stack",
      client: "Proyecto propio",
      category: "github",
      value: "Next.js 15 + Supabase",
      period: "2026",
      icon: "hub",
      color: "purple",
      tags: ["TypeScript", "Next.js 15", "Supabase", "SaaS", "CRM/ERP"],
      github_url: "https://github.com/jorgeahmed/hecho-metrics",
      summary_es: "SaaS full-stack para agencia SEO: CRM, ERP, módulo financiero con 2FA, portal de clientes, motor de auditoría y enrutamiento multi-tenant por subdominio.",
      summary_en: "Full-stack SaaS for SEO agency: CRM, ERP, finance module with 2FA, client portal, audit engine, and multi-tenant subdomain routing.",
      challenge_es: "Construir una plataforma SaaS completa con múltiples clientes en subdominios independientes, autenticación segura 2FA y módulos de negocio integrados desde cero.",
      challenge_en: "Build a complete SaaS platform managing multiple clients in independent subdomains with secure 2FA authentication and integrated business modules from scratch.",
      solution_es: "Arquitectura multi-tenant con Next.js 15 App Router, Supabase como backend (auth + DB + storage), módulos CRM y ERP, 2FA, portal de clientes y motor de auditoría SEO.",
      solution_en: "Multi-tenant architecture with Next.js 15 App Router, Supabase as backend (auth + DB + storage), CRM and ERP modules, 2FA, client portal, and SEO audit engine.",
      outcome_es: "Plataforma en producción con arquitectura multi-tenant, autenticación 2FA, módulos de finanzas y auditoría SEO funcionales.",
      outcome_en: "Production platform with multi-tenant architecture, 2FA authentication, functional finance and SEO audit modules.",
      stack: ["TypeScript", "Next.js 15", "Supabase", "PostgreSQL", "Tailwind CSS", "2FA", "Multi-tenant"],
      metrics_es: [{ label: "Stack", value: "Next.js 15" }, { label: "DB", value: "Supabase" }, { label: "Auth", value: "2FA" }],
      metrics_en: [{ label: "Stack", value: "Next.js 15" }, { label: "DB", value: "Supabase" }, { label: "Auth", value: "2FA" }],
    },
    {
      id: "quotebot-vision",
      title: "QuoteBot Vision — IA para Cotizaciones",
      client: "Mantenimiento Sinai (interno)",
      category: "github",
      value: "2h → 2 min (−98%)",
      period: "2026",
      icon: "smart_toy",
      color: "blue",
      tags: ["Flutter", "Dart", "Gemini Vision", "IA", "Construcción"],
      github_url: "https://github.com/jorgeahmed/quotebot-vision",
      summary_es: "App móvil Flutter + Gemini Vision AI que transforma cotizaciones de construcción de 2 horas a 2 minutos mediante análisis visual de fotos del sitio.",
      summary_en: "Flutter + Gemini Vision AI mobile app that transforms construction quotes from 2 hours to 2 minutes through visual photo analysis of the site.",
      challenge_es: "El proceso de cotización de obra tardaba 2+ horas por visita. Con múltiples proyectos simultáneos en Mantenimiento Sinai, era un cuello de botella crítico.",
      challenge_en: "Construction quoting took 2+ hours per site visit. With multiple simultaneous projects at Mantenimiento Sinai, it was a critical bottleneck.",
      solution_es: "App Flutter que usa Gemini Vision AI para analizar fotos del sitio y generar automáticamente cotizaciones estructuradas con materiales, labor y cronograma.",
      solution_en: "Flutter app using Gemini Vision AI to analyze site photos and automatically generate structured quotes with materials, labor, and timeline.",
      outcome_es: "De 2 horas a 2 minutos por cotización. Reducción del 98% en tiempo. Adoptado como proceso estándar en Mantenimiento Sinai.",
      outcome_en: "From 2 hours to 2 minutes per quote. 98% time reduction. Adopted as standard process at Mantenimiento Sinai.",
      stack: ["Flutter", "Dart", "Gemini Vision AI", "Firebase", "Mobile Development"],
      metrics_es: [{ label: "Reducción", value: "98%" }, { label: "Antes", value: "2 horas" }, { label: "Ahora", value: "2 min" }],
      metrics_en: [{ label: "Reduction", value: "98%" }, { label: "Before", value: "2 hours" }, { label: "Now", value: "2 min" }],
    },
    {
      id: "seismic-iot",
      title: "Seismic IoT Alert System",
      client: "SeismicAI (respaldo técnico)",
      category: "github",
      value: "Python + IoT",
      period: "2025",
      icon: "sensors",
      color: "orange",
      tags: ["Python", "IoT", "Seismic", "ML", "Edge"],
      github_url: "https://github.com/jorgeahmed/seismic-iot-alert-system",
      summary_es: "Sistema de alerta sísmica IoT en Python. Respaldo técnico del trabajo realizado en SeismicAI para las instalaciones de BBVA.",
      summary_en: "IoT seismic alert system in Python. Technical backing of work done at SeismicAI for BBVA installations.",
      challenge_es: "Documentar y prototipar la arquitectura de sistemas de alerta sísmica con integración IoT para proyectos enterprise de banca.",
      challenge_en: "Document and prototype seismic alert system architecture with IoT integration for enterprise banking projects.",
      solution_es: "Implementación en Python de sistema de detección sísmica con sensores IoT, procesamiento en tiempo real y protocolo de alertas automatizadas.",
      solution_en: "Python implementation of seismic detection system with IoT sensors, real-time processing, and automated alert protocol.",
      outcome_es: "Repositorio técnico que respalda la experiencia práctica en SeismicAI/BBVA con código real demostrable.",
      outcome_en: "Technical repository backing practical SeismicAI/BBVA experience with demonstrable real code.",
      stack: ["Python", "IoT Sensors", "Edge Computing", "Real-time Processing", "ML"],
      metrics_es: [{ label: "Lenguaje", value: "Python" }, { label: "Tipo", value: "IoT + ML" }, { label: "Sector", value: "Banca/Sísmica" }],
      metrics_en: [{ label: "Language", value: "Python" }, { label: "Type", value: "IoT + ML" }, { label: "Sector", value: "Banking/Seismic" }],
    },
    {
      id: "mqtt-glide",
      title: "MQTT + GlideApp — IoT en Tiempo Real",
      client: "Proyecto IoT propio",
      category: "github",
      value: "Node.js + MQTT",
      period: "2024",
      icon: "sensors",
      color: "cyan",
      tags: ["JavaScript", "Node.js", "MQTT", "GlideApps", "IoT"],
      github_url: "https://github.com/jorgeahmed/MQTT-Google-Sheet-y-GlideApp",
      summary_es: "Integración Node.js + MQTT para actualización en tiempo real de Google Sheets con interfaz GlideApp. Monitoreo IoT de sensores industriales sin costo.",
      summary_en: "Node.js + MQTT integration for real-time Google Sheets updates with GlideApp interface. Zero-cost industrial IoT sensor monitoring.",
      challenge_es: "Crear un sistema de monitoreo IoT asequible que actualice datos de sensores industriales en tiempo real con interfaz accesible para operadores sin conocimiento técnico.",
      challenge_en: "Create an affordable IoT monitoring system that updates industrial sensor data in real-time with an accessible interface for non-technical operators.",
      solution_es: "Node.js se suscribe a tópicos MQTT de sensores industriales, procesa mensajes y actualiza Google Sheets automáticamente. GlideApp genera la interfaz visual desde los datos.",
      solution_en: "Node.js subscribes to industrial sensor MQTT topics, processes messages and automatically updates Google Sheets. GlideApp generates the visual interface from the data.",
      outcome_es: "Sistema IoT en producción: datos de sensores en tiempo real visibles en app móvil sin inversión en software costoso.",
      outcome_en: "IoT monitoring system in production: real-time sensor data visible on mobile app without costly software investment.",
      stack: ["Node.js", "MQTT", "GlideApps", "Google Sheets API", "JavaScript", "IoT"],
      metrics_es: [{ label: "Stack", value: "Node+MQTT" }, { label: "UI", value: "GlideApps" }, { label: "Latencia", value: "Real-time" }],
      metrics_en: [{ label: "Stack", value: "Node+MQTT" }, { label: "UI", value: "GlideApps" }, { label: "Latency", value: "Real-time" }],
    },
    {
      id: "fashion-mnist",
      title: "Fashion MNIST — Deep Learning en Vertex AI",
      client: "Proyecto de aprendizaje ML",
      category: "github",
      value: "TensorFlow + Vertex AI",
      period: "2024",
      icon: "model_training",
      color: "indigo",
      tags: ["Python", "TensorFlow", "Google Cloud", "Deep Learning", "Vertex AI"],
      github_url: "https://github.com/jorgeahmed/fashion-mnist-project",
      summary_es: "Clasificador de imágenes de moda con Deep Learning entrenado en Google Cloud Vertex AI. Accuracy ~92% en dataset Fashion MNIST.",
      summary_en: "Fashion image classifier with Deep Learning trained on Google Cloud Vertex AI. ~92% accuracy on Fashion MNIST dataset.",
      challenge_es: "Entrenar y desplegar un modelo de clasificación de imágenes con Deep Learning usando infraestructura cloud de Google, como parte del aprendizaje en ML aplicado.",
      challenge_en: "Train and deploy an image classification model with Deep Learning using Google cloud infrastructure, as part of applied ML learning.",
      solution_es: "Red neuronal convolucional en TensorFlow/Keras entrenada sobre Fashion MNIST, desplegada en Google Cloud Vertex AI para predicciones en tiempo real.",
      solution_en: "Convolutional neural network in TensorFlow/Keras trained on Fashion MNIST, deployed on Google Cloud Vertex AI for real-time predictions.",
      outcome_es: "Modelo con ~92% de accuracy desplegado en Vertex AI. Proyecto demostrativo de capacidades ML sobre infraestructura cloud enterprise.",
      outcome_en: "Model with ~92% accuracy deployed on Vertex AI. Demonstrative project of ML capabilities on enterprise cloud infrastructure.",
      stack: ["Python", "TensorFlow", "Google Cloud Vertex AI", "Jupyter", "NumPy", "Matplotlib"],
      metrics_es: [{ label: "Accuracy", value: "~92%" }, { label: "Platform", value: "Vertex AI" }, { label: "Tipo", value: "Deep Learning" }],
      metrics_en: [{ label: "Accuracy", value: "~92%" }, { label: "Platform", value: "Vertex AI" }, { label: "Type", value: "Deep Learning" }],
    },
  ],

  // ── HABILIDADES ──────────────────────────────────────────
  skills: {
    pm_es: ['Gestión de Portafolios', 'Estimación de Costos', 'Gestión de Riesgos', 'Stakeholders C-Level', 'WBS / Cronograma', 'Control de Cambios', 'Gestión de Alcance', 'Lecciones Aprendidas'],
    pm_en: ['Portfolio Management', 'Cost Estimation', 'Risk Management', 'C-Level Stakeholders', 'WBS / Scheduling', 'Change Control', 'Scope Management', 'Lessons Learned'],
    tech_es: ['IA / Gemini API', 'Python', 'TypeScript / Next.js', 'Flutter / Dart', 'Node.js / MQTT', 'SQL / PostgreSQL', 'REST APIs', 'Git / GitHub', 'TensorFlow / ML', 'IoT Firmware'],
    tech_en: ['AI / Gemini API', 'Python', 'TypeScript / Next.js', 'Flutter / Dart', 'Node.js / MQTT', 'SQL / PostgreSQL', 'REST APIs', 'Git / GitHub', 'TensorFlow / ML', 'IoT Firmware'],
    infra_es: ['Edge Computing', 'IoT / MQTT / LoRa', 'CCTV Industrial PoE', 'Redes Aruba / Cisco', 'Fibra Óptica', 'Transformadores HV', 'SAT / VPN', 'BMS / HVAC', 'SCADA', 'LPR Automation'],
    infra_en: ['Edge Computing', 'IoT / MQTT / LoRa', 'Industrial CCTV PoE', 'Aruba / Cisco Networks', 'Fiber Optic', 'HV Transformers', 'SAT / VPN', 'BMS / HVAC', 'SCADA', 'LPR Automation'],
    management_es: ['Scrum / Kanban', 'PMBOK Framework', 'MS Project', 'Jira / ClickUp', 'Presupuestación', 'Contratos B2B', 'OKR / KPI Design', 'Gestión de Equipos', 'Change Management', 'Reportes Ejecutivos'],
    management_en: ['Scrum / Kanban', 'PMBOK Framework', 'MS Project', 'Jira / ClickUp', 'Budgeting', 'B2B Contracts', 'OKR / KPI Design', 'Team Management', 'Change Management', 'Executive Reporting'],
  },

  CHAT_SUGGESTIONS: [
    '¿Qué proyectos de IA ha liderado Jorge?',
    '¿Cuál es su experiencia con clientes Fortune 500?',
    '¿Qué tecnologías domina?',
    '¿Cuál es el proyecto de mayor presupuesto que ha gestionado?',
    '¿Qué metodologías de gestión usa?',
    "What's Jorge's experience with IoT and infrastructure?",
    'Tell me about his AI and software development projects',
    'Analyze his fit for a CTO or Tech Director role',
  ],
};
